# Kubernetes Secrets Management
# Using Sealed Secrets or External Secrets Operator for production

# Database credentials (sealed/encrypted)
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: marketing-automation
spec:
  encryptedData:
    username: AgBy... # Sealed secret - replace with actual sealed value
    password: AgAg... # Sealed secret - replace with actual sealed value
    postgres-url: AgBw... # Sealed secret - replace with actual sealed value
  template:
    metadata:
      name: postgres-credentials
      namespace: marketing-automation
    type: Opaque

---
# Application secrets (sealed/encrypted)
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secrets
  namespace: marketing-automation
spec:
  encryptedData:
    jwt-secret: AgBk... # Sealed secret - replace with actual sealed value
    session-secret: AgCd... # Sealed secret - replace with actual sealed value
    encryption-key: AgDe... # Sealed secret - replace with actual sealed value
  template:
    metadata:
      name: app-secrets
      namespace: marketing-automation
    type: Opaque

---
# API credentials (sealed/encrypted)
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-secrets
  namespace: marketing-automation
spec:
  encryptedData:
    sendgrid-api-key: AgEf... # Sealed secret - replace with actual sealed value
    stripe-secret-key: AgFg... # Sealed secret - replace with actual sealed value
    stripe-publishable-key: AgGh... # Sealed secret - replace with actual sealed value
    stripe-webhook-secret: AgHi... # Sealed secret - replace with actual sealed value
    mailchimp-api-key: AgIj... # Sealed secret - replace with actual sealed value
    twitter-api-key: AgJk... # Sealed secret - replace with actual sealed value
    twitter-api-secret: AgKl... # Sealed secret - replace with actual sealed value
    instagram-access-token: AgLm... # Sealed secret - replace with actual sealed value
  template:
    metadata:
      name: api-secrets
      namespace: marketing-automation
    type: Opaque

---
# Database connection secrets for Redis
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: database-secrets
  namespace: marketing-automation
spec:
  encryptedData:
    redis-url: AgMn... # Sealed secret - replace with actual sealed value
    postgres-url: AgNo... # Sealed secret - replace with actual sealed value
  template:
    metadata:
      name: database-secrets
      namespace: marketing-automation
    type: Opaque

---
# Backup credentials
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backup-credentials
  namespace: marketing-automation
spec:
  encryptedData:
    ACCESS_KEY_ID: AgOp... # Sealed secret - replace with actual sealed value
    SECRET_ACCESS_KEY: AgPq... # Sealed secret - replace with actual sealed value
  template:
    metadata:
      name: backup-credentials
      namespace: marketing-automation
    type: Opaque

---
# Grafana credentials
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-user: AgQr... # Sealed secret - replace with actual sealed value
    admin-password: AgRs... # Sealed secret - replace with actual sealed value
  template:
    metadata:
      name: grafana-credentials
      namespace: monitoring
    type: Opaque

---
# External Secrets Operator Configuration (Alternative approach)
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: marketing-automation
spec:
  provider:
    vault:
      server: "https://vault.yourdomain.com"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "marketing-automation"
          serviceAccountRef:
            name: marketing-automation-sa

---
# External Secret for database credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-credentials-external
  namespace: marketing-automation
spec:
  refreshInterval: 300s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: postgres-credentials
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: marketing-automation/database
      property: username
  - secretKey: password
    remoteRef:
      key: marketing-automation/database
      property: password
  - secretKey: postgres-url
    remoteRef:
      key: marketing-automation/database
      property: url

---
# External Secret for API credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-secrets-external
  namespace: marketing-automation
spec:
  refreshInterval: 600s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: api-secrets
    creationPolicy: Owner
  data:
  - secretKey: sendgrid-api-key
    remoteRef:
      key: marketing-automation/apis
      property: sendgrid_key
  - secretKey: stripe-secret-key
    remoteRef:
      key: marketing-automation/apis
      property: stripe_secret
  - secretKey: stripe-publishable-key
    remoteRef:
      key: marketing-automation/apis
      property: stripe_public
  - secretKey: stripe-webhook-secret
    remoteRef:
      key: marketing-automation/apis
      property: stripe_webhook

---
# Image Pull Secrets for private registries
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: marketing-automation
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiZ2l0aHViLXVzZXIiLCJwYXNzd29yZCI6ImdocF90b2tlbiIsImVtYWlsIjoiZGV2b3BzQHlvdXJkb21haW4uY29tIiwiYXV0aCI6IloybDBhSEpwWW1SbGRtVnNiM0JsY2pwblpXaDNPamhwYm5KaGJHUnBhR0U5In19fQ==

---
# ConfigMap for non-sensitive configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: marketing-automation
  labels:
    app: marketing-automation-hub
data:
  NODE_ENV: "production"
  PORT: "3000"
  METRICS_PORT: "9090"
  LOG_LEVEL: "info"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "100"
  SESSION_TIMEOUT: "3600000"
  CORS_ORIGIN: "https://marketing-hub.yourdomain.com,https://yourdomain.com"
  API_VERSION: "v1"
  
  # Feature flags
  ENABLE_ANALYTICS: "true"
  ENABLE_SOCIAL_MEDIA: "true"
  ENABLE_EMAIL_AUTOMATION: "true"
  ENABLE_MONITORING: "true"
  
  # Performance settings
  MAX_CONCURRENT_REQUESTS: "1000"
  REQUEST_TIMEOUT: "30000"
  CONNECTION_POOL_SIZE: "20"
  
  # Security settings
  HELMET_ENABLED: "true"
  CSRF_PROTECTION: "true"
  RATE_LIMITING_ENABLED: "true"